version: "3.3"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "PTOBuilder"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"