## ------------ Paragon The Overprime Builder ------------
## ----- Test config and config organisation example -----

PTOBuilder_storage:
  host: "localhost"
  port: "5432"
  database: "PTOBuilder"
  username: "admin"
  password: "admin"
  maxAttempt: 5

WebServer:
  host: "localhost"
  port: "8080"
  writeTimeout: 15
  readTimeout: 15